import type { AdminEventSummary, DisplayState } from "@/lib/types";

export const demoDisplayToken = "demo-display-token";

export const demoSummary: AdminEventSummary = {
  event: {
    id: "demo-event",
    name: "会场抽奖",
    slug: "demo-event",
    display_token: demoDisplayToken,
    status: "active",
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  runtime: {
    event_id: "demo-event",
    phase: "idle",
    current_draw_session_id: null,
    current_prize_id: "demo-prize-1",
    selected_group_ids: [],
    revision: 1,
    settings: {
      acceleration_ms: 1500,
      deceleration_ms: 2500,
      suspense_ms: 1000,
      shake_strength: 4,
      animation_enabled: true,
      music_enabled: true,
      tension_volume: 0.55,
      reveal_volume: 0.75,
      keyboard_shortcuts_enabled: true,
      allow_group_repeat_win: false,
      exclude_prize_winners: true,
      exclude_event_winners: false,
    },
    updated_at: new Date().toISOString(),
  },
  groups: Array.from({ length: 6 }, (_, index) => ({
    id: `demo-group-${index + 1}`,
    event_id: "demo-event",
    name: `第${["一", "二", "三", "四", "五", "六"][index]}组`,
    participant_count: 8 + index,
    enabled: true,
    sort_order: index + 1,
    allow_repeat_win: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  })),
  prizes: [
    {
      id: "demo-prize-1",
      event_id: "demo-event",
      name: "幸运奖",
      description: "现场互动奖品",
      total_draws: 3,
      completed_draws: 0,
      draw_count_per_round: 1,
      enabled: true,
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "demo-prize-2",
      event_id: "demo-event",
      name: "神秘礼",
      description: "课程专属礼品",
      total_draws: 2,
      completed_draws: 0,
      draw_count_per_round: 1,
      enabled: true,
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  records: [],
  displayOnline: false,
  lastHeartbeatAt: null,
};

export const demoDisplayState: DisplayState = {
  event: demoSummary.event,
  runtime: demoSummary.runtime!,
  currentPrize: { id: "demo-prize-1", name: "幸运奖" },
  currentSession: null,
  revealedGroups: [],
  audioAssets: [],
  displayOnline: false,
  lastHeartbeatAt: null,
};
